version: "3"

networks:
  MYNETWORK:

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./app/symfony_project:/var/www/app
      - ./nginx/default_symfony.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks: 
      - MYNETWORK
  
  php:
    build: ./php
    volumes:
      - ./app/symfony_project:/var/www/app
      - ./php/starter.sh:/usr/local/bin/starter.sh
    ports:
      - "9000:9000"
    command:
      - starter.sh
    networks: 
      - MYNETWORK