version: "3"

networks:
  MYNETWORK:

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks: 
      - MYNETWORK
  
  php:
    image: php:7.2-fpm
    volumes:
      - ./app:/var/www/app
    networks: 
      - MYNETWORK