version: "3"

networks:
  MYNETWORK:

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks: 
      - MYNETWORK
  
  php:
    build: ./php
    volumes:
      - ./www:/var/www
      - ./php/starter.sh:/usr/local/bin/starter.sh
    ports:
      - "9000:9000"
    command:
      - starter.sh
    depends_on:
      - mariadb
    networks: 
      - MYNETWORK

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=q1w2e3r4t5y6
      - MYSQL_DATABASE=mydb
    volumes:
      - ./database:/var/lib/mysql
    networks: 
      - MYNETWORK

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=db
      ports:
          - "8080:80"
      volumes:
          - /sessions
      depends_on:
        - mariadb
      networks: 
        - MYNETWORK